config/routes.rb
     Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'users/sessions'}
  resources :users, :only => [:new] do
    collection do
      get 'search'
    end
    get 'credentials'
    post 'update_credentials'
  end

  root 'welcome#index'

  resources :studio_connections do
    get 'repositories'
    get 'dashboard'
    get 'dashboard/query/:query_id' => "studio_connections#dash_query", :as => "dash_query"
    get 'repositories/:repo_name' => "studio_connections#show_repo", :as => "show_repo"
    get 'repositories/:repo_name/input:path' =>"studio_connections#browse_repo", :as => "browse_repo", :constraints => { :path => /\/.+(?=\.html\z|\.template\z)/ }
    get 'repositories/:repo_name/history/:guid' => "studio_connections#history", :as => "object_history"
    get 'repositories/:repo_name/object/:guid' => "studio_connections#object_dump", :as => "object_browse"
    get 'repositories/:repo_name/object_shape/:guid' => "studio_connections#object_shape", :as => "object_shape"
    get 'repositories/:repo_name/stats' => "studio_connections#repo_stats", :as => "repo_stats"
    get 'model_version' => "studio_connections#version_stats", :as => "version_stats" #-------------------------------------------------------------MODEL_VERSION
    get 'repositories/:repo_name/stats/:object' => "studio_connections#repo_object_stats", :as => "repo_object_stats"
    get 'repositories/:repo_name/conformity' => "studio_connections#conformity", :as => "conformity"
    get 'repositories/:repo_name/users' => "studio_connections#repo_users", :as => "repo_users"
    get 'repositories/:repo_name/users/:id' => "studio_connections#repo_user", :as => "repo_user"
    get 'users' => "studio_connections#users", :as => "users"
    get 'users/:username' => "studio_connections#user", :as => "user"
  end

  resources :settings, :only => [:index] do
    collection do
      get 'connections'
      resources :statistics, :only => [:index]  do
        collection do
          get 'edit_categories'
          patch 'update_categories'
          get 'edit_headers'
          patch 'update_headers'
        end
      end
      get 'indexes'
      get 'admins'
      post 'admins' => 'users#update_admins'
    end
  end

  resources :statistics, :only => [] do
    collection do
      get 'new_category'
      get 'new_header'
    end
  end

  resources :studio_indices do
    get 'env_dump'
  end

  resources :babylon_test, :only => [:index] do
    collection do
      get 'test'
    end
  end

end

app/controllers/studio_connections_controller.rb
class StudioConnectionsController < ApplicationController
  before_action :authenticate_user!

  def new
    @connection = StudioConnection.new
  end

  def create
    @connection = StudioConnection.new(studio_connection_params)

    if @connection.valid? then
      if @connection.save! then
        flash[:notice] = "New connection created"
        redirect_to root_path
      else
        flash[:error] = "Failed to create new connection"
        redirect_to :back
      end
    else
      flash[:error] = "connection invalid"
      redirect_to :back
    end
  end

  def show
    @connection = StudioConnection.find(params[:id])
    @user_credential = current_user.user_credentials.where(:studio_connection_id => params[:id]).first

    respond_to do |format|
      format.html
      format.template{
      }
    end
  end

  #  GET    /studio_connections/:id
  # always template
  def repositories
    @repositories = StudioConnection.find(params[:studio_connection_id]).list_repo current_user

    respond_to do |format|
      format.template
    end
  end

  #edit the template
  #  GET    /studio_connections/:id/edit(.:format)
  def edit
    @connection = StudioConnection.find params[:id]

    respond_to do |format|
      format.html
    end
  end

  #  PATCH  /studio_connections/:id
  def update
    @connection = StudioConnection.find params[:id]

    @connection.assign_attributes studio_connection_params

    if @connection.valid? then
      if @connection.save! then
        flash[:notice] = "Studio Connection settings updated"
        redirect_to root_path
      else
        flash[:error] = "Failed to Update Studio Connection"
        redirect_to :back
      end
    else
      flash[:error] = "Wrong!!"
      redirect_to :back
    end
  end

  # GET    /studio_connections/:studio_connection_id/repositories/:repo_name
  # recommended by optional argument
  # guid  gets the parent guid
  def show_repo
    @connection = StudioConnection.find params[:studio_connection_id]

    #check permission
    @allowed = @connection.user_allowed? current_user,  params[:repo_name]

    js :repository => params[:repo_name],
      :allowed => @allowed,
      :content_path =>
        studio_connection_show_repo_path(params[:studio_connection_id], params[:repo_name]) + ".template"

    #conn = StudioConnection.find(params[:studio_connection_id])
    respond_to do |format|
      format.html {
        if !@allowed then
          render :file => "public/403.html", :status => :forbidden
        end
      }
      format.template{
        conn = StudioConnection.find(params[:studio_connection_id])
        render :template => "studio_connections/browse_repo.template", :locals => {
           :'@path' => "/", :'@repository' => params[:repo_name], :'@content' => conn.browse(params[:repo_name])
         }
      }
    end
  end

  #GET    /studio_connections/:studio_connection_id/repositories/:repo_name:path(.:format)
  # :format is mandatory, otherwise path cannot be found
  def browse_repo
      @repository = params[:repo_name]
      @path = params[:path]
      @connection = StudioConnection.find(params[:studio_connection_id])
      if !params.has_key?(:guid) then
        conn = StudioConnection.find(params[:studio_connection_id])
        params[:guid] = conn.get_guid @repository, @path
      end

      js :content_path =>
        "/studio_connections/#{params[:studio_connection_id]}/repositories/#{@repository}/input/#{@path}.template?guid=#{params[:guid]}",
        :history_path => studio_connection_object_history_path(params[:studio_connection_id], @repository, params[:guid]),
        :object_dump_path => studio_connection_object_browse_path(params[:studio_connection_id], @repository, params[:guid],
          :format => :template)
      #somehow this doesn't work
      #studio_connection_browse_repo_path(params[:studio_connection_id], @repository,
      #  :path => @path, :guid => params[:guid]) + ".template"

      respond_to do |format|
        format.html{
        }

        format.template {
          conn = StudioConnection.find(params[:studio_connection_id])
          @content = conn.browse(params[:repo_name], params[:path], params[:guid])
        }
      end
  end

  # GET    /studio_connections/:studio_connection_id/history/:repo_name/:guid
  # template only
  def history
    @history = StudioConnection.find(params[:studio_connection_id]).show_history(params[:repo_name], params[:guid])
    respond_to do |format|
      format.template
    end
  end

  # given a repo name and guid, get the oracle entry of said guid, template only
  # GET    /studio_connections/:studio_connection_id/object/:repo_name/:guid
  def object_dump
    conn = StudioConnection.find(params[:studio_connection_id])
    @object = conn.get_object_dump params[:repo_name], params[:guid]

    respond_to do |format|
      format.template
    end
  end

  #  GET    /studio_connections/:studio_connection_id/stats/:repo_name(.:format)
  def repo_stats
    @connection = StudioConnection.find(params[:studio_connection_id])
    @allowed = @connection.user_allowed? current_user, params[:repo_name]

    @stats = @connection.get_stats params[:repo_name]

    js :stats => @stats, :repo_name => params[:repo_name]

    respond_to do |format|
      format.html {
        if !@allowed then
          render :file => "public/403.html", :status => :forbidden
        end
      }
    end

  end
#-----------------------------------------------------------------------KIV---------------------------------------------------
  # GET    /studio_connections/:studio_connection_id/stats/:repo_name/:object
  def repo_object_stats
    sc = StudioConnection.find(params[:studio_connection_id])
    @results = sc.query "select insert_date, count(id) as insert_count
      from #{params[:repo_name]}.#{params[:object]}
      group by insert_date order by insert_date"
    @header_info = StatHeader.lookup params[:object]
    js :stats => @results
  end
#-------------------------------------------------------------------------KIV------------------------------------------------

#-----------------------------------------------------------------------under_testing---------------------------------------------------
  def version_stats
    sc = StudioConnection.find(params[:studio_connection_id])
    @result_ver = sc.query"select model_version, count(*) as model_count
          from sks_sys.sds_project
          group by model_version"
    js :ver_stats => @result_ver
    
    @result_ver_count = sc.query"select count(model_version) as total_count
            from sks_sys.sds_project"
  end

  # order by project
#-------------------------------------------------------------------------under_testing------------------------------------------------

  #  DELETE /studio_connections/:id
  def destroy
    sc = StudioConnection.find(params[:id])

    if sc.nil? then
      flash[:notice] = "Connection now found"
    else
      sc.destroy
      flash[:notice] = "Studio Connection deleted"
    end

    redirect_to connections_settings_path
  end

  #GET    /studio_connections/:studio_connection_id/conformity/:repo_name
  def conformity
    @connection = StudioConnection.find(params[:studio_connection_id])
    @allowed = @connection.user_allowed? current_user, params[:repo_name]

    respond_to do |format|
      format.html {
        if !@allowed then
          render :file => "public/403.html", :status => :forbidden
        end
      }
      format.template {
        @dir_list = StudioConnection.find(params[:studio_connection_id]).tree params[:repo_name]
      }
    end
  end

  #  GET    /studio_connections/:studio_connection_id/users(.:format)
  def users
    @connection = StudioConnection.find(params[:studio_connection_id])
    if @connection.user_is_admin? current_user then
      @users = @connection.query "select account, create_date, first_name, last_name, email_address from sks_sys.sds_user"
    else
      @users = []
    end
  end

  #  GET    /studio_connections/:studio_connection_id/users/:username
  def user
    sc = StudioConnection.find(params[:studio_connection_id])
    @interface = sc.query "select account from sks_sys.sds_pipe where sds_user = '#{params[:username]}'"
    @privilege = sc.query("select privilege from sks_sys.sds_user where account = '#{params[:username]}'").first

    respond_to do |format|
      format.template
    end
  end

  def repo_users
    sc = StudioConnection.find(params[:studio_connection_id])
    allowed = sc.user_allowed? current_user, params[:repo_name]

     js :users
     respond_to do |format|
       format.html{
        if !allowed then
          render :file => "public/403.html", :status => :forbidden
        else
          @users = sc.query "
            select
              users.account, users.first_name, last_name, email_address, users.create_Date
            from sks_sys.sds_user users, sks_sys.sds_pipe pipe
            where
              users.account = pipe.sds_user
              and pipe.account = '#{params[:repo_name]}'
           "
        end
       }
       format.template
     end
  end

  #GET    /studio_connections/:studio_connection_id/dashboard
  # get dashbaord values
  def dashboard
    @connection = StudioConnection.find(params[:studio_connection_id])

    if @connection.user_is_admin? current_user then
      @dashboard = @connection.dashboard
    else
      render :status => :unauthorized
    end
  end

  # GET    /studio_connections/:studio_connection_id/dashboard/query/:query_id
  def dash_query
    sc = StudioConnection.find(params[:studio_connection_id])
    @query_data = sc.dashboard_query(params[:query_id])

    respond_to do |format|
      format.template
    end
  end

  # GET    /studio_connections/:studio_connection_id/repositories/:repo_name/object_shape/:guid
  # returns the info about the object shape in json format
  def object_shape
    sc = StudioConnection.find(params[:studio_connection_id])

app/helpers/studio_connections_helper.rb
module StudioConnectionsHelper
  # find stuff inside the dir list and remove the stuff in the dir list
  def findings dir_list, search_pattern

    #some agreed standards
    project_type ="(?:BLKENTRY|BLKREVAL|PEM|PREDRILL|POSTDRILL|RGN)"
    vintange = "[0-9]{4}"
    project_sequence = "[[:upper:]]{1}"
    project_title = "#{project_type}_[A-Z0-9]+_#{vintange}"

    search_pattern = search_pattern.gsub /!project_title!/, "#{project_title}"
    search_term = dir_list.select{|x| /#{search_pattern}/ =~ x}

    if search_term.empty? then
      "None detected"
    else
      dir_list.delete_if{|x| /#{search_pattern}/ =~ x }
      content_tag(:ul, search_term.map{ |x| content_tag :li, x.gsub(/~/, "/")}.join.html_safe).html_safe
    end
  end
end

app/views/studio_connections/admin_list.template.haml
- if connections.empty? then
  %ul.list-group
    %li.list-group-item No Connections
- else
  %ul.list-group
    - connections.each do |connection|
      %li.list-group-item
        %a{ :href => edit_studio_connection_path(connection)}
          %i.fa.fa-cog
        #{connection.username}@//#{connection.oracle_host }:#{connection.port}/#{connection.oracle_instance}
        .pull-right
          = form_tag studio_connection_path(connection), :method => :delete do
            %button.btn.btn-danger.btn-xs{ :type => 'submit', :data => { :confirm => "Are you sure? "}}
              %i.fa.fa-minus

app/views/studio_connections/browse_header.template.haml
%ul.nav.nav-tabs.nav-justified
  %li{ :class => active == "repo" ? "active" : "" }
    %a{ :role => "presentation", :href => studio_connection_path(params[:studio_connection_id]) } Repositories
  %li{ :class => active == "model-version" ? "active" : "" }
    %a{ :role => "presentation", :href => studio_connection_version_stats_path(params[:studio_connection_id]) } Model Version
  %li{ :class => active == "dashboard" ? "active" : "" }
    %a{ :role => "presentation", :href => studio_connection_dashboard_path(params[:studio_connection_id]) } Dashboard
  %li{ :class => active == "users" ? "active" : "" }
    %a{ :role => "presentation", :href => studio_connection_users_path(params[:studio_connection_id]) } Users

app/views/studio_connections/browse_repo.html.haml
- content_for :head do
  = "-  #{@connection.oracle_instance} > #{params[:repo_name]} > #{params[:path]}"

.col-sm-12
  %h1.page-header{:style => 'word-wrap:brea-word;'} #{ params[:path].split("/").last}
  %ol.breadcrumb
    %li
      #{link_to StudioConnection.find(params[:studio_connection_id]).oracle_instance, studio_connection_path(params[:studio_connection_id])}
    %li
      #{link_to params[:repo_name],  studio_connection_show_repo_path(params[:studio_connection_id], params[:repo_name])}
    %li.active
      #{params[:path]}
.col-sm-12
  .table-responsive
    %table.table.table-hover.sortable
      %thead
        %tr
          %th.col-sm-8 Object
          %th.col-sm-2 Updated
          %th.col-sm-2 By
      %tbody#repo-content
        %tr#loading-content
          %td
            %i.fa.fa-cog.fa-spin
            Loading Content...
.col-sm-12
  %h2.page-header Object Info
  #object-info
    %i.fa.fa-cog.fa-spin
    Loading Content...
.col-sm-12
  %h2.page-header History
  .table-responsive
    %table.table
      %thead
        %tr
          %th.col-sm-2 Date
          %th.col-sm-8 Action
          %th.col-sm-2 By
      %tbody#history-content
        %tr
          %td{ :colspan => 3}
            %i.fa.fa-cog.fa-spin
            Loading Content...

app/views/studio_connections/browse_repo.template.haml
- if @path == "/" then
  - @content.each do |key,value|
    %tr
      %td #{link_to value[:name], "/studio_connections/#{params[:studio_connection_id]}/repositories/#{params[:repo_name]}/input/#{value[:name]}.html?guid=#{value[:guid]}"}
      %td #{ time_ago_in_words(value[:object_update_date])}
      %td #{ value[:object_update_user]}
- else
  - if @content.empty? then
    %tr
      %td{ :colspan => 3 } No child detected
  - else
    - @content.each do |key,value|
      %tr
        %td #{link_to value[:name], "/studio_connections/#{params[:studio_connection_id]}/repositories/#{params[:repo_name]}/input#{params[:path]}/#{value[:name]}.html?guid=#{value[:guid]}"}
        %td #{ time_ago_in_words(value[:object_update_date])}
        %td #{ value[:object_update_user]}

app/views/studio_connections/dashboard.html.haml
- content_for :head do
  = "- #{@connection.oracle_instance} - Dashboard"

.col-sm-12
  %h1.page-header Dashboard
  %ol.breadcrumb
    %li.active
      #{StudioConnection.find(params[:studio_connection_id]).oracle_instance}
  = render :template => "studio_connections/browse_header.template", :locals => { :active => "dashboard"}
  %div
    - if @connection.user_is_admin? current_user then
      %br
      - @dashboard.each do |dash|
        .panel.panel-default
          .panel-heading
            %h3 #{dash[:NAME]}
          .panel-body
            %h4.page-header Description
            %p #{dash[:REMARKS]}
            %h4.page-header Results
            %p
              %button.btn.btn-default.request-result{ :type => 'button', :data => { :queryid => dash[:ID],
                :querypath => studio_connection_dash_query_path(params[:studio_connection_id], dash[:ID],
                  :format => :template), :target => "#result-#{dash[:ID]}"}  }
                %i.fa.fa-refresh
              Hit Refresh to get the data
            .result-table{ :id => "result-#{dash[:ID]}"}
    - else
      %br
      .panel.panel-default
        .panel-heading
          %h3 Unauthorized
        .panel-body
          %p You can't see this

app/views/studio_connections/edit.html.haml
.row
  .col-sm-6
    %h1.page-header Edit Connection
    %p
      = render "form"

app/views/studio_connections/index.template.haml
- if connections.nil? or connections.empty? then
  %ul.list-group
    %li.list-group-item
      %a{ :href => new_studio_connection_path } No Connections. Create one
- else
  %ul.list-group
    - connections.each do |connection|
      %li.list-group-item
        %a{ :href => studio_connection_path(connection), :style => "word-wrap:break-word;"}
          #{connection.username}@//#{connection.oracle_host }/#{connection.oracle_instance}

app/views/studio_connections/object_dump.template.haml
.table-responsive
  %table.table.table-hover.sortable
    %thead
      %tr
        %th Property
        %th Value
    %tbody
      - @object.each_pair do |key,value|
        %tr
          %td #{ key }
          %td #{ value.class == String ? simple_format(value) : value }

app/views/studio_connections/repo_object_stats.html.haml
- content_for :head do
  = "- #{params[:repo_name]} > Statistics > #{@header_info[:display_name]}"

.row
  .col-sm-12
    %h1.page-header #{@header_info[:display_name]}
    %ul.breadcrumb
      %li
        #{link_to StudioConnection.find(params[:studio_connection_id]).oracle_instance, studio_connection_path(params[:studio_connection_id])}
      %li
        #{link_to params[:repo_name],  studio_connection_show_repo_path(params[:studio_connection_id], params[:repo_name])}
      %li
        #{link_to "Statistics", studio_connection_repo_stats_path(params[:studio_connection_id], params[:repo_name])}
      %li.active #{ @header_info[:display_name]}
    #object-stats-chart
    %table.table.table-responsive
      %thead
        %tr
          %th
          %th Insert Date
          %th Insert Count
      %tbody
        - @results.each do |line|
          %tr
            %td
              %a{ :href => "#", :data => { :time =>  line[:INSERT_DATE].to_i }}
                %i.fa.fa-toggle-down
            %td #{ line[:INSERT_DATE]}
            %td #{ line[:INSERT_COUNT].to_i}

app/views/studio_connections/repo_stats.html.haml
- content_for :head do
  = "- #{@connection.oracle_instance} > #{params[:repo_name]}"

.col-sm-12
  %h1.page-header #{params[:repo_name]}
  %ul.nav.nav-tabs.nav-justified
    %li
      %a{ :role => "presentation", :href => studio_connection_show_repo_path(params[:studio_connection_id], params[:repo_name])} Repository
    %li.active
      %a{ :role => "presentation", :href=>  studio_connection_repo_stats_path(params[:studio_connection_id], params[:repo_name])} Statistics
    %li
      %a{ :role => "presentation", :href=>  studio_connection_conformity_path(params[:studio_connection_id], params[:repo_name])} Conformity
    %li
      %a{ :role => "presentation", :href=>  studio_connection_repo_users_path(params[:studio_connection_id], params[:repo_name])} Users
  %br
  #repo-stats-chart{ :style => "height: 80vh" }
  %table.table.table-hover
    %thead
      %tr
        %th Propoerty
        %th Count
        %th Category
    %tbody
      - @stats.each do |line|
        %tr
          %td #{ link_to line[:ENTITY], studio_connection_repo_object_stats_path(params[:studio_connection_id], params[:repo_name], line[:ENTITY_TBL])}
          %td #{ line[:ENTITY_COUNT].to_i}
          %td #{ line[:ENTITY_CAT]}

app/views/studio_connections/repo_users.html.haml
- content_for :head do
  = "- #{params[:repo_name]} > Users"

.col-sm-12
  %h1.page-header #{params[:repo_name]}
  %ul.nav.nav-tabs.nav-justified
    %li
      %a{ :role => "presentation", :href => studio_connection_show_repo_path(params[:studio_connection_id], params[:repo_name])} Repository
    %li
      %a{ :role => "presentation", :href=>  studio_connection_repo_stats_path(params[:studio_connection_id], params[:repo_name])} Statistics
    %li
      %a{ :role => "presentation", :href=>  studio_connection_conformity_path(params[:studio_connection_id], params[:repo_name])} Conformity
    %li.active
      %a{ :role => "presentation", :href=>  studio_connection_repo_users_path(params[:studio_connection_id], params[:repo_name])} Users
  = render :template => "studio_connections/users.template", :locals => { :'@users' => @users}

app/views/studio_connections/show_repo.html.haml
- content_for :head do
  = "- #{@connection.oracle_instance} > #{params[:repo_name]}"

.col-sm-12
  %h1.page-header #{params[:repo_name]}
  = render :template => "studio_connections/browse_header.template", :locals => { :active => "repo"}
  %br
  %ol.breadcrumb
    %li
      #{link_to StudioConnection.find(params[:studio_connection_id]).oracle_instance, studio_connection_path(params[:studio_connection_id])}
    %li.active /
  .table-responsive
    %table.table.table-hover.sortable
      %thead
        %tr
          %th.col-sm-8 Object
          %th.col-sm-2 Updated
          %th.col-sm-2 By
      %tbody#repo-content
        %tr#loading-content
          %td
            %i.fa.fa-cog.fa-spin
            Loading Content...

app/views/studio_connections/users.html.haml
- content_for :head do
  = "- #{@connection.oracle_instance} - Users"

.col-sm-12
  %h1.page-header Users
  %ol.breadcrumb
    %li.active
      #{StudioConnection.find(params[:studio_connection_id]).oracle_instance}
<<<<<<< HEAD
  %ul.nav.nav-tabs.nav-justified
    %li
      %a{ :role => "presentation", :href => studio_connection_path(params[:studio_connection_id]) } Repositories
    %li
      %a{ :role => "presentation", :href => studio_connection_version_stats_path(params[:studio_connection_id]) } Model Version
    %li
      %a{ :role => "presentation", :href => studio_connection_dashboard_path(params[:studio_connection_id]) } Dashboard
    %li.active
      %a{ :role => "presentation", :href => studio_connection_users_path(params[:studio_connection_id]) } Users
=======
  = render :template => "studio_connections/browse_header.template", :locals => { :active => "users"}
>>>>>>> refs/remotes/origin/erwinkarim
  = render :template => "studio_connections/users.template", :locals => { :'@users' => @users}

app/views/studio_connections/users.template.haml
.table-responsive
  %table.table.table-hover
    %thead
      %tr
        %th
        %th User
        %th Name
        %th Email
        %th Created
    %tbody
      - @users.each do |user|
        %tr
          %td
            %a{ :href => "##{user[:ACCOUNT]}", :data => { :toggle => 'collapse'}, :role => 'button'}
              %i.fa.fa-toggle-down
          %td #{ user[:ACCOUNT] }
          %td #{ user[:FIRST_NAME]} #{ user[:LAST_NAME]}
          %td #{ user[:EMAIL_ADDRESS]}
          %td #{ user[:CREATE_DATE]}
        %tr.collapse{ :id => user[:ACCOUNT] ,
          :data => { :load => studio_connection_user_path(params[:studio_connection_id], user[:ACCOUNT], :format => 'template')} }