config/routes.rb
     Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'users/sessions'}
  resources :users, :only => [:new] do
    collection do
      get 'search'
    end
    get 'credentials'
    post 'update_credentials'
  end

  root 'welcome#index'

  resources :studio_connections do
    get 'repositories'
    get 'dashboard'
    get 'dashboard/query/:query_id' => "studio_connections#dash_query", :as => "dash_query"
    get 'repositories/:repo_name' => "studio_connections#show_repo", :as => "show_repo"
    get 'repositories/:repo_name/input:path' =>"studio_connections#browse_repo", :as => "browse_repo", :constraints => { :path => /\/.+(?=\.html\z|\.template\z)/ }
    get 'repositories/:repo_name/history/:guid' => "studio_connections#history", :as => "object_history"
    get 'repositories/:repo_name/object/:guid' => "studio_connections#object_dump", :as => "object_browse"
    get 'repositories/:repo_name/object_shape/:guid' => "studio_connections#object_shape", :as => "object_shape"
    get 'repositories/:repo_name/stats' => "studio_connections#repo_stats", :as => "repo_stats"
    get 'model_version' => "studio_connections#version_stats", :as => "version_stats" #-------------------------------------------------------------MODEL_VERSION
    get 'repositories/:repo_name/stats/:object' => "studio_connections#repo_object_stats", :as => "repo_object_stats"
    get 'repositories/:repo_name/conformity' => "studio_connections#conformity", :as => "conformity"
    get 'repositories/:repo_name/users' => "studio_connections#repo_users", :as => "repo_users"
    get 'repositories/:repo_name/users/:id' => "studio_connections#repo_user", :as => "repo_user"
    get 'users' => "studio_connections#users", :as => "users"
    get 'users/:username' => "studio_connections#user", :as => "user"
  end

  resources :settings, :only => [:index] do
    collection do
      get 'connections'
      resources :statistics, :only => [:index]  do
        collection do
          get 'edit_categories'
          patch 'update_categories'
          get 'edit_headers'
          patch 'update_headers'
        end
      end
      get 'indexes'
      get 'admins'
      post 'admins' => 'users#update_admins'
    end
  end

  resources :statistics, :only => [] do
    collection do
      get 'new_category'
      get 'new_header'
    end
  end

  resources :studio_indices do
    get 'env_dump'
  end

  resources :babylon_test, :only => [:index] do
    collection do
      get 'test'
    end
  end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @categories = StatCategory.all
    @headers = StatHeader.all
  end

  def edit_categories
    @categories = StatCategory.all
  end

  def new_category
    js false
    respond_to do |format|
      format.template
      format.html{
        render :template => "statistics/new_category.template", :content_type => "text/template"
      }
    end
  end

  def update_categories
    #process categories

    #update current ones

    #delete ones not in the list

    #add new ones
    flash[:notice] = "Categories Updated"
    redirect_to edit_categories_statistics_path
  end

  #  GET    /settings/statistics/edit_headers
  def edit_headers
    @headers = StatHeader.all
  end

  def new_header
    js false
    respond_to do |format|
      format.template
      format.html{
        render :template => "statistics/new_header.template", :content_type => "text/template"
      }
    end
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/edit_categories.html.haml
.row
  .col-sm-12
    %h1.page-header Categories
  .col-sm-12
    %ul.breadcrumb
      %li
        %a{:href => settings_path} Settings
      %li
        %a{:href => statistics_path } Statistics
      %li.active Categories
  .col-sm-12
    = form_tag update_categories_statistics_path, :method => :patch do
      %table.table
        %tbody#category-list
          - @categories.each do |category|
            = render :template => "statistics/new_category.template", :locals => { :category => category}
          %tr#new-category-tr
            %td
              %a.btn.btn-primary#new-category
                %i.fa.fa-plus
      %button.btn.btn-primary{ :type => 'submit'} Update Category

app/views/statistics/edit_headers.html.haml
.row
  .col-sm-12
    %h1.page-header Edit Headers
  .col-sm-12
    %ul.breadcrumb
      %li
        %a{:href => settings_path} Settings
      %li
        %a{:href => statistics_path } Statistics
      %li.active Headers
  .col-sm-12
    = form_tag update_headers_statistics_path, :method => :patch do
      %table.table
        %tbody#header-list
          - @headers.each do |header|
            = render :template => 'statistics/new_header.template', :locals => { :header => header }
          %tr#new-header-tr
            %td
              %a.btn.btn-primary#new-header
                %i.fa.fa-plus
      %button.btn.btn-primary{ :type => 'submit'} Update Headers

app/views/statistics/index.html.haml
- content_for :head do
  = "- Settings > Statistics"
.col-sm-12
  %h1.page-header Statistics
  %ul.breadcrumb
    %li
      %a{ :href => settings_path} Settings
    %li.active
      Statistics
  %h2.page-header Categories
  - if @categories.empty? then
    %p No Categories yet
  - else
    .row
      .col-sm-4
        %ul.list-group
        - @categories.each do |category|
          %li.list-group-item #{category.name}
  %br
  %p
    %a.btn.btn-primary{ :disabled => true, :href => '#' } Edit Categories
    \-- Comming soon


  %h2.page-header Headers
  %p Note: You need to update the categories section to use new categories
  - if @headers.empty? then
    %p No headers detected
  - else
    %table.table
      %thead
        %tr
          %th Entry
          %th Display name
          %th Category
      %tbody
        - @headers.each do |header|
          %tr
            %td #{ header.name }
            %td #{ header.display_name }
            %td #{ header.stat_category.name }
  %p
    %a.btn.btn-primary{ :href => '#' } Edit Headers
    \-- Comming soon

app/views/statistics/new_category.template.haml
%tr.category-row
  %td.col-sm-6
    %input.form-control{ :type => 'text', :name => "category[]", :placeholder => "Type New Category",
      :value => (defined? category) ? category.name : ''}
    %input{ :type => "hidden", :name => "category_id[]", :value => (defined? category) ? category.id : -1 }
  %td
    %a.btn.btn-danger.delete-category
      %i.fa.fa-minus

app/views/statistics/new_header.template.haml
%tr.header-row
  %td.col-sm-6
    %input.form-control{ :type => 'text', :name => "headers[]", :placeholder => "Type New Header",
      :value => (defined? header) ? header.name : ''}
    %input{ :type => "hidden", :name => "header_id[]", :value => (defined? header) ? header.id : -1 }
  %td.col-sm-4
    = select_tag('header_cat[]', options_for_select(StatCategory.all.map{ |x| [x.name, x.id] },
      (defined? header) ? header.stat_category.id : nil ), :class => 'form-control' )
  %td
    %a.btn.btn-danger.delete-category
      %i.fa.fa-minus