config/routes.rb
     Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'users/sessions'}
  resources :users, :only => [:new] do
    collection do
      get 'search'
    end
    get 'credentials'
    post 'update_credentials'
  end

  root 'welcome#index'

  resources :studio_connections do
    get 'repositories'
    get 'dashboard'
    get 'dashboard/query/:query_id' => "studio_connections#dash_query", :as => "dash_query"
    get 'repositories/:repo_name' => "studio_connections#show_repo", :as => "show_repo"
    get 'repositories/:repo_name/input:path' =>"studio_connections#browse_repo", :as => "browse_repo", :constraints => { :path => /\/.+(?=\.html\z|\.template\z)/ }
    get 'repositories/:repo_name/history/:guid' => "studio_connections#history", :as => "object_history"
    get 'repositories/:repo_name/object/:guid' => "studio_connections#object_dump", :as => "object_browse"
    get 'repositories/:repo_name/object_shape/:guid' => "studio_connections#object_shape", :as => "object_shape"
    get 'repositories/:repo_name/stats' => "studio_connections#repo_stats", :as => "repo_stats"
    get 'model_version' => "studio_connections#version_stats", :as => "version_stats" #-------------------------------------------------------------MODEL_VERSION
    get 'repositories/:repo_name/stats/:object' => "studio_connections#repo_object_stats", :as => "repo_object_stats"
    get 'repositories/:repo_name/conformity' => "studio_connections#conformity", :as => "conformity"
    get 'repositories/:repo_name/users' => "studio_connections#repo_users", :as => "repo_users"
    get 'repositories/:repo_name/users/:id' => "studio_connections#repo_user", :as => "repo_user"
    get 'users' => "studio_connections#users", :as => "users"
    get 'users/:username' => "studio_connections#user", :as => "user"
  end

  resources :settings, :only => [:index] do
    collection do
      get 'connections'
      resources :statistics, :only => [:index]  do
        collection do
          get 'edit_categories'
          patch 'update_categories'
          get 'edit_headers'
          patch 'update_headers'
        end
      end
      get 'indexes'
      get 'admins'
      post 'admins' => 'users#update_admins'
    end
  end

  resources :statistics, :only => [] do
    collection do
      get 'new_category'
      get 'new_header'
    end
  end

  resources :studio_indices do
    get 'env_dump'
  end

  resources :babylon_test, :only => [:index] do
    collection do
      get 'test'
    end
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def connections
    @connections = StudioConnection.all
  end

  def indexes
    @indexes = StudioIndex.all
  end

  def admins
    @admins = User.where(:admin => true)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/admins.html.haml
- content_for :head do
  = "- Settings > Admins"
.col-sm-12
  %h1.page-header Admins
  %ul.breadcrumb
    %li
      %a{ :href => settings_path} Settings
    %li.active
      Admins
  %p People in this list can view everything, otherwise other users need to put in credentials
  %p User must be logged in first because the name can be put into admin
  .well
    The default admin of this site is #{ ENV['default_admin']}
  %h2.page-header List
  = form_tag admins_settings_path do
    #admin-list
      - @admins.each do |admin|
        = render :template => 'users/form.template', :locals => { :user => admin }
    .form-group
      %button.btn.btn-primary#new-admin{ :type => 'button' }
        %i.fa.fa-plus
    .form-group
      %button.btn.btn-primary#update-admins{ :type => 'submit' } Update

app/views/settings/connections.html.haml
- content_for :head do
  = "- Settings > Connections"
.col-sm-12
  %h1.page-header Connections
  %ul.breadcrumb
    %li
      %a{ :href => settings_path} Settings
    %li.active
      Connections
  = render :template => "studio_connections/admin_list.template", :locals => { :connections => @connections }
  %p
    %a.btn.btn-primary{ :href => new_studio_connection_path} New Connection

app/views/settings/index.html.haml
- content_for :head do
  = "- Settings"
.col-sm-12
  %h1.page-header Local Settings
  = render :template => "settings/interface.template", :locals => { :target_picture => "images/settings-credentials.jpg",
    :target_path => user_credentials_path(current_user), :target_name => 'Credentials'}
- if current_user.username == ENV["default_admin"] || current_user.admin? then
  .col-sm-12
    %h1.page-header Master Settings
    = render :template => "settings/interface.template", :locals => { :target_picture => "images/settings-conn.png",
      :target_path => connections_settings_path, :target_name => 'Connections'}
    = render :template => "settings/interface.template", :locals => { :target_picture => "images/settings-stats.png",
      :target_path => statistics_path, :target_name => 'Statistics'}
    = render :template => "settings/interface.template", :locals => { :target_picture => "images/settings-indexes.png",
      :target_path => indexes_settings_path , :target_name => 'Indexes'}
    = render :template => "settings/interface.template", :locals => { :target_picture => "images/settings-admins.jpg",
      :target_path => admins_settings_path, :target_name => 'Admins'}

app/views/settings/indexes.html.haml
- content_for :head do
  = "- Settings > Indexes"
.col-sm-12
  %h1.page-header Indexes
  %ul.breadcrumb
    %li
      %a{ :href => settings_path} Settings
    %li.active
      Indexes
  = render :template => "studio_indices/admin_list.template", :locals => { :indexes => @indexes }
  %p
    %a.btn.btn-primary{ :href => new_studio_index_path} New Index

app/views/settings/interface.template.haml
.col-xs-6.col-md-3
	.thumbnail
		%img{:src => target_picture, :width => 256, :height => 256 }
		.caption
			%a.center-block.btn.btn-default{ :href => target_path } #{ target_name }