config/routes.rb
     Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'users/sessions'}
  resources :users, :only => [:new] do
    collection do
      get 'search'
    end
    get 'credentials'
    post 'update_credentials'
  end

  root 'welcome#index'

  resources :studio_connections do
    get 'repositories'
    get 'dashboard'
    get 'dashboard/query/:query_id' => "studio_connections#dash_query", :as => "dash_query"
    get 'repositories/:repo_name' => "studio_connections#show_repo", :as => "show_repo"
    get 'repositories/:repo_name/input:path' =>"studio_connections#browse_repo", :as => "browse_repo", :constraints => { :path => /\/.+(?=\.html\z|\.template\z)/ }
    get 'repositories/:repo_name/history/:guid' => "studio_connections#history", :as => "object_history"
    get 'repositories/:repo_name/object/:guid' => "studio_connections#object_dump", :as => "object_browse"
    get 'repositories/:repo_name/object_shape/:guid' => "studio_connections#object_shape", :as => "object_shape"
    get 'repositories/:repo_name/stats' => "studio_connections#repo_stats", :as => "repo_stats"
    get 'model_version' => "studio_connections#version_stats", :as => "version_stats" #-------------------------------------------------------------MODEL_VERSION
    get 'repositories/:repo_name/stats/:object' => "studio_connections#repo_object_stats", :as => "repo_object_stats"
    get 'repositories/:repo_name/conformity' => "studio_connections#conformity", :as => "conformity"
    get 'repositories/:repo_name/users' => "studio_connections#repo_users", :as => "repo_users"
    get 'repositories/:repo_name/users/:id' => "studio_connections#repo_user", :as => "repo_user"
    get 'users' => "studio_connections#users", :as => "users"
    get 'users/:username' => "studio_connections#user", :as => "user"
  end

  resources :settings, :only => [:index] do
    collection do
      get 'connections'
      resources :statistics, :only => [:index]  do
        collection do
          get 'edit_categories'
          patch 'update_categories'
          get 'edit_headers'
          patch 'update_headers'
        end
      end
      get 'indexes'
      get 'admins'
      post 'admins' => 'users#update_admins'
    end
  end

  resources :statistics, :only => [] do
    collection do
      get 'new_category'
      get 'new_header'
    end
  end

  resources :studio_indices do
    get 'env_dump'
  end

  resources :babylon_test, :only => [:index] do
    collection do
      get 'test'
    end
  end

end

app/controllers/babylon_test_controller.rb
class BabylonTestController < ApplicationController
  def index
  end
end

app/helpers/babylon_test_helper.rb
module BabylonTestHelper
end

app/views/babylon_test/index.html.haml
%h1.page-header Babylon Test
%p Surface in pspex > W_SARAWAKREGIONAL_MYS >  /input/Interpretation:RGN_SARAWAKREGIONAL_2015/hazwan_minhat/Surfaces/MMU (SURFACE)/MMU[T]_DW2C
%table.table
  %thead
    %tr
      %th Item
      %th Value
  %tbody
    %tr
      %td Instance
      %td pspex
    %tr
      %td Project
      %td W_SARAWAKREGIONAL_MYS
    %tr
      %td Path
      %td /input/Interpretation:RGN_SARAWAKREGIONAL_2015/hazwan_minhat/Surfaces/MMU (SURFACE)/MMU[T]_DW2C
    %tr
      %td Table Name
      %td DovRegularHeightSurface
    %tr
      %td Table ID
      %td 487229
    %tr
      %td Table GUID
      %td ED96FFFA88ED42AEB4FC471AD96331D2
%p Should get this:-
%p
  %img{ :src => "images/surface.png", :style => "width:100%;"}
%p Now we got this:-
%p #{link_to "Test", test_babylon_test_index_path }

app/views/babylon_test/test.html.haml
- content_for :other_js do
  = javascript_include_tag 'http://cdn.babylonjs.com/2-2/babylon.js'
end
%canvas#renderCanvas{ :style => "width:100%; height:85vh;" }